name: Build and Publish Notebooks

on:
  push:
    branches:
      - production  # Default branch
    # paths:
      # - 'work/**/*.ipynb'  # Watch only files in the "work" folder

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Prepare Output Directory and Copy Data
      - name: Prepare Output Directory and Copy Data
        run: |
          mkdir -p docs
          cp -r ./data ./work  # Copy the data directory to work for notebook references
          echo "Contents of work folder before conversion:"
          ls -R work

      # Step 5: Convert Notebooks and Preserve Folder Structure
      - name: Convert Notebooks and Preserve Folder Structure
        run: |
          echo "<html><body><h1>Index of Notebooks</h1><ul>" > docs/index.html  # Create the Index page

          for notebook in $(find ./ -name "*.ipynb"); do
            relative_dir=$(dirname "$notebook" | sed 's|^./work/||')  # Extract the relative path within 'work'
            output_dir="docs/$relative_dir"
            mkdir -p "$output_dir"
            
            # Convert the notebook to HTML
            jupyter nbconvert --execute --to html "$notebook" --output-dir "$output_dir"
            
            # Copy all contents of the notebook's parent directory to the corresponding output directory
            parent_dir=$(dirname "$notebook")
            cp -r "$parent_dir/"* "$output_dir/"

            # Add a link to the index page
            notebook_name=$(basename "$notebook" .ipynb)
            echo "<li><a href=\"$relative_dir/$notebook_name.html\">$notebook_name</a></li>" >> docs/index.html
          done

          # Close the Index page HTML
          echo "</ul></body></html>" >> docs/index.html

          echo "Contents of docs folder after conversion:"
          ls -R docs

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
