name: Build and Publish Notebooks

on:
  push:
    branches:
      - main  # Default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # # Step 4: Prepare Output Directory and Copy Data
      # - name: Prepare Output Directory and Copy Data
      #   run: |
      #     mkdir -p docs
      #     cp -r ./data ./work  

      # Step 5: Convert Notebooks and Preserve Folder Structure
      - name: Convert Notebooks and Preserve Folder Structure
        run: |
          # Start the Index Page with TailwindCSS CDN
          echo "<html lang='en'>
                  <head>
                    <meta charset='UTF-8'>
                    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
                    <title>Index of Notebooks</title>
                    <script src='https://cdn.tailwindcss.com'></script>
                  </head>
                  <body class='bg-gray-100 p-8'>
                    <div class='container mx-auto'>
                      <h1 class='text-4xl font-semibold text-center mb-4'>Index of Notebooks</h1>
                      <ul class='space-y-4'>" > docs/index.html

          # Function to close open details
          close_open_details() {
            while [ $current_depth -gt $1 ]; do
              echo "</ul></details>" >> docs/index.html
              current_depth=$((current_depth - 1))
            done
          }

          # Initialize variables
          current_depth=0
          prev_dir=""

          # Process each notebook
          for notebook in $(find ./ -name "*.ipynb" | sort); do
            relative_dir=$(dirname "$notebook" | sed 's|^./||')  # Extract relative path
            output_dir="docs/$relative_dir"
            mkdir -p "$output_dir"
            
            # Convert notebook to HTML
            jupyter nbconvert --execute --to html "$notebook" --output-dir "$output_dir"
            
            # Copy contents of the parent directory
            parent_dir=$(dirname "$notebook")
            cp -r "$parent_dir/"* "$output_dir/" || true

            # Build navigation structure
            IFS="/" read -ra DIR_PARTS <<< "$relative_dir"
            for (( i=0; i<${#DIR_PARTS[@]}; i++ )); do
              if [ $i -ge $current_depth ] || [ "${DIR_PARTS[i]}" != "$(echo $prev_dir | cut -d/ -f$((i + 1)))" ]; then
                close_open_details $i
                echo "<details class='bg-white rounded-lg shadow-md'>
                        <summary class='p-4 text-xl font-medium bg-gray-200 hover:bg-gray-300 rounded-t-lg'>
                          ${DIR_PARTS[i]}
                        </summary>
                        <ul class='pl-6 space-y-2'>" >> docs/index.html
                current_depth=$((current_depth + 1))
              fi
            done

            # Add notebook link
            notebook_name=$(basename "$notebook" .ipynb)
            echo "<li>
                    <a href=\"$relative_dir/$notebook_name.html\" class='p-2 text-lg text-blue-600 hover:text-blue-800'>$notebook_name</a>
                  </li>" >> docs/index.html

            prev_dir=$relative_dir
          done

          # Close all remaining open tags
          close_open_details 0

          # Close the index page HTML
          echo "</ul></div></body></html>" >> docs/index.html

          echo "Contents of docs folder after conversion:"
          ls -R docs


     # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages