name: Build and Publish Notebooks

on:
  push:
    branches:
      - main  # Default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # # Step 4: Prepare Output Directory and Copy Data
      # - name: Prepare Output Directory and Copy Data
      #   run: |
      #     mkdir -p docs
      #     cp -r ./data ./work  

      # Step 5: Convert Notebooks and Preserve Folder Structure
      - name: Convert Notebooks and Preserve Folder Structure
        run: |
          # Start the Index Page with TailwindCSS CDN
          echo "<html lang='en'>
                  <head>
                    <meta charset='UTF-8'>
                    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
                    <title>Index of Notebooks</title>
                    <script src='https://cdn.tailwindcss.com'></script>
                  </head>
                  <body class='bg-gray-100 p-8'>
                    <div class='container mx-auto'>
                      <h1 class='text-4xl font-semibold text-center mb-2'>Index of Notebooks</h1>
                      <a href='/README.md' class='text-md text-center mb-8 block'>README</a>
                      <ul class='space-y-4'>" > docs/index.html

          # Process notebooks and organize them by parent directory
          for notebook in $(find ./ -name "*.ipynb"); do
            relative_dir=$(dirname "$notebook" | sed 's|^./||')  # Extract the relative path
            output_dir="docs/$relative_dir"
            mkdir -p "$output_dir"
            
            # Convert the notebook to HTML
            jupyter nbconvert --execute --to html "$notebook" --output-dir "$output_dir"
            
            # Copy all contents of the notebook's parent directory to the corresponding output directory
            parent_dir=$(dirname "$notebook")
            cp -r "$parent_dir/"* "$output_dir/"

            # Build the navigation structure
            IFS="/" read -ra DIR_PARTS <<< "$relative_dir"
            nav_path=""
            for (( i=0; i<${#DIR_PARTS[@]}; i++ )); do
              nav_path="$nav_path/${DIR_PARTS[i]}"
              # Open a new details tag for each directory level if not already opened
              if ! grep -q "<summary>${DIR_PARTS[i]}</summary>" docs/index.html; then
                echo "<details class='bg-white rounded-lg shadow-md'>
                        <summary class='cursor-pointer p-4 text-xl font-medium bg-gray-200 hover:bg-gray-300 rounded-t-lg'>
                          ${DIR_PARTS[i]}
                        </summary>
                        <ul class='pl-6 space-y-2'>" >> docs/index.html
              fi
            done

            # Add the notebook link within the appropriate directory
            notebook_name=$(basename "$notebook" .ipynb)
            echo "<li>
                    <a href=\"$relative_dir/$notebook_name.html\" class='p-2 text-lg text-blue-600 hover:text-blue-800'>$notebook_name</a>
                  </li>" >> docs/index.html
          done

          # Close all open tags for directories
          grep -o "<details" docs/index.html | while read -r _; do
            echo "</ul></details>" >> docs/index.html
          done

          # Close the Index page HTML
          echo "</ul></div></body></html>" >> docs/index.html

          echo "Contents of docs folder after conversion:"
          ls -R docs


     # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages