name: Build and Publish Notebooks

on:
  push:
    branches:
      - production  # Default branch
    # paths:
      # - 'work/**/*.ipynb'  # Watch only files in the "work" folder

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # Step 4: Prepare Output Directory and Copy Data
      - name: Prepare Output Directory and Copy Data
        run: |
          mkdir -p docs
          cp -r ./data ./work  # Copy the data directory to work for notebook references
          echo "Contents of work folder before conversion:"
          ls -R work

      # Step 5: Convert Notebooks and Preserve Folder Structure
      - name: Convert Notebooks and Preserve Folder Structure
        run: |
          for notebook in $(find ./ -name "*.ipynb"); do
            relative_dir=$(dirname "$notebook" | sed 's|^./work/||')
            output_dir="docs/$relative_dir"
            mkdir -p "$output_dir"
            jupyter nbconvert --execute --to html "$notebook" --output-dir "$output_dir"
            # Copy corresponding data folders to the output directory
            input_data_dir="$(dirname "$notebook")"
            if [ -d "$input_data_dir" ]; then
              cp -r "$input_data_dir" "$output_dir/"
            fi
          done
          echo "Contents of docs folder after conversion:"
          ls -R docs

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
