name: Build and Publish Notebooks

on:
  push:
    branches:
      - production  # Default branch
    # paths:
      # - 'work/**/*.ipynb'  # Watch only files in the "work" folder

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Prepare Output Directory and Copy Data
      - name: Prepare Output Directory and Copy Data
        run: |
          mkdir -p docs
          cp -r ./data ./work  # Copy the data directory to work for notebook references
          echo "Contents of work folder before conversion:"
          ls -R work

      # Step 5: Convert Notebooks and Preserve Folder Structure
      - name: Convert Notebooks and Preserve Folder Structure
        run: |
          # Start the Index Page with TailwindCSS CDN
          echo "<html lang='en'>
                  <head>
                    <meta charset='UTF-8'>
                    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
                    <title>Index of Notebooks</title>
                    <script src='https://cdn.tailwindcss.com'></script>
                  </head>
                  <body class='bg-gray-100 p-8'>
                    <div class='container mx-auto'>
                      <h1 class='text-4xl font-semibold text-center mb-8'>Index of Notebooks</h1>
                      <ul class='space-y-4'>" > docs/index.html

          for notebook in $(find ./ -name "*.ipynb"); do
            relative_dir=$(dirname "$notebook" | sed 's|^./work/||')  # Extract the relative path within 'work'
            output_dir="docs/$relative_dir"
            mkdir -p "$output_dir"
            
            # Convert the notebook to HTML
            jupyter nbconvert --execute --to html "$notebook" --output-dir "$output_dir"
            
            # Copy all contents of the notebook's parent directory to the corresponding output directory
            parent_dir=$(dirname "$notebook")
            cp -r "$parent_dir/"* "$output_dir/"

            # Add a styled link to the index page with TailwindCSS
            notebook_name=$(basename "$notebook" .ipynb)
            echo "<a href=\"$relative_dir/$notebook_name.html\" class='p-4 text-xl font-medium text-blue-600 hover:text-blue-800'>
                    <li class='bg-white rounded-lg shadow-md hover:bg-blue-50'>
                      $notebook_name
                    </li>
                  </a>" >> docs/index.html
          done

          # Close the Index page HTML
          echo "</ul></div></body></html>" >> docs/index.html

          echo "Contents of docs folder after conversion:"
          ls -R docs
     # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages